package com.yourapp.ui.components

data class CountryItem(
    val name: String,
    val flag: String,
    val code: String
)

val fullCountryList = listOf(
    CountryItem("Afghanistan", "🇦🇫", "+93"),
    CountryItem("Albania", "🇦🇱", "+355"),
    CountryItem("Algeria", "🇩🇿", "+213"),
    CountryItem("Andorra", "🇦🇩", "+376"),
    CountryItem("Angola", "🇦🇴", "+244"),
    CountryItem("Antigua and Barbuda", "🇦🇬", "+1-268"),
    CountryItem("Argentina", "🇦🇷", "+54"),
    CountryItem("Armenia", "🇦🇲", "+374"),
    CountryItem("Australia", "🇦🇺", "+61"),
    CountryItem("Austria", "🇦🇹", "+43"),
    CountryItem("Azerbaijan", "🇦🇿", "+994"),

    CountryItem("Bahamas", "🇧🇸", "+1-242"),
    CountryItem("Bahrain", "🇧🇭", "+973"),
    CountryItem("Bangladesh", "🇧🇩", "+880"),
    CountryItem("Barbados", "🇧🇧", "+1-246"),
    CountryItem("Belarus", "🇧🇾", "+375"),
    CountryItem("Belgium", "🇧🇪", "+32"),
    CountryItem("Belize", "🇧🇿", "+501"),
    CountryItem("Benin", "🇧🇯", "+229"),
    CountryItem("Bhutan", "🇧🇹", "+975"),
    CountryItem("Bolivia", "🇧🇴", "+591"),
    CountryItem("Bosnia and Herzegovina", "🇧🇦", "+387"),
    CountryItem("Botswana", "🇧🇼", "+267"),
    CountryItem("Brazil", "🇧🇷", "+55"),
    CountryItem("Brunei", "🇧🇳", "+673"),
    CountryItem("Bulgaria", "🇧🇬", "+359"),
    CountryItem("Burkina Faso", "🇧🇫", "+226"),
    CountryItem("Burundi", "🇧🇮", "+257"),

    CountryItem("Cabo Verde", "🇨🇻", "+238"),
    CountryItem("Cambodia", "🇰🇭", "+855"),
    CountryItem("Cameroon", "🇨🇲", "+237"),
    CountryItem("Canada", "🇨🇦", "+1"),
    CountryItem("Central African Republic", "🇨🇫", "+236"),
    CountryItem("Chad", "🇹🇩", "+235"),
    CountryItem("Chile", "🇨🇱", "+56"),
    CountryItem("China", "🇨🇳", "+86"),
    CountryItem("Colombia", "🇨🇴", "+57"),
    CountryItem("Comoros", "🇰🇲", "+269"),
    CountryItem("Congo (DRC)", "🇨🇩", "+243"),
    CountryItem("Congo (Republic)", "🇨🇬", "+242"),
    CountryItem("Costa Rica", "🇨🇷", "+506"),
    CountryItem("Croatia", "🇭🇷", "+385"),
    CountryItem("Cuba", "🇨🇺", "+53"),
    CountryItem("Cyprus", "🇨🇾", "+357"),
    CountryItem("Czech Republic", "🇨🇿", "+420"),

    CountryItem("Denmark", "🇩🇰", "+45"),
    CountryItem("Djibouti", "🇩🇯", "+253"),
    CountryItem("Dominica", "🇩🇲", "+1-767"),
    CountryItem("Dominican Republic", "🇩🇴", "+1-809"),

    CountryItem("Ecuador", "🇪🇨", "+593"),
    CountryItem("Egypt", "🇪🇬", "+20"),
    CountryItem("El Salvador", "🇸🇻", "+503"),
    CountryItem("Equatorial Guinea", "🇬🇶", "+240"),
    CountryItem("Eritrea", "🇪🇷", "+291"),
    CountryItem("Estonia", "🇪🇪", "+372"),
    CountryItem("Eswatini", "🇸🇿", "+268"),
    CountryItem("Ethiopia", "🇪🇹", "+251"),

    CountryItem("Fiji", "🇫🇯", "+679"),
    CountryItem("Finland", "🇫🇮", "+358"),
    CountryItem("France", "🇫🇷", "+33"),

    CountryItem("Gabon", "🇬🇦", "+241"),
    CountryItem("Gambia", "🇬🇲", "+220"),
    CountryItem("Georgia", "🇬🇪", "+995"),
    CountryItem("Germany", "🇩🇪", "+49"),
    CountryItem("Ghana", "🇬🇭", "+233"),
    CountryItem("Greece", "🇬🇷", "+30"),
    CountryItem("Grenada", "🇬🇩", "+1-473"),
    CountryItem("Guatemala", "🇬🇹", "+502"),
    CountryItem("Guinea", "🇬🇳", "+224"),
    CountryItem("Guinea-Bissau", "🇬🇼", "+245"),
    CountryItem("Guyana", "🇬🇾", "+592"),

    CountryItem("Haiti", "🇭🇹", "+509"),
    CountryItem("Honduras", "🇭🇳", "+504"),
    CountryItem("Hungary", "🇭🇺", "+36"),

    CountryItem("Iceland", "🇮🇸", "+354"),
    CountryItem("India", "🇮🇳", "+91"),
    CountryItem("Indonesia", "🇮🇩", "+62"),
    CountryItem("Iran", "🇮🇷", "+98"),
    CountryItem("Iraq", "🇮🇶", "+964"),
    CountryItem("Ireland", "🇮🇪", "+353"),
    CountryItem("Israel", "🇮🇱", "+972"),
    CountryItem("Italy", "🇮🇹", "+39"),

    CountryItem("Jamaica", "🇯🇲", "+1-876"),
    CountryItem("Japan", "🇯🇵", "+81"),
    CountryItem("Jordan", "🇯🇴", "+962"),

    CountryItem("Kazakhstan", "🇰🇿", "+7"),
    CountryItem("Kenya", "🇰🇪", "+254"),
    CountryItem("Kiribati", "🇰🇮", "+686"),
    CountryItem("Kuwait", "🇰🇼", "+965"),
    CountryItem("Kyrgyzstan", "🇰🇬", "+996"),

    CountryItem("Laos", "🇱🇦", "+856"),
    CountryItem("Latvia", "🇱🇻", "+371"),
    CountryItem("Lebanon", "🇱🇧", "+961"),
    CountryItem("Lesotho", "🇱🇸", "+266"),
    CountryItem("Liberia", "🇱🇷", "+231"),
    CountryItem("Libya", "🇱🇾", "+218"),
    CountryItem("Liechtenstein", "🇱🇮", "+423"),
    CountryItem("Lithuania", "🇱🇹", "+370"),
    CountryItem("Luxembourg", "🇱🇺", "+352"),

    CountryItem("Madagascar", "🇲🇬", "+261"),
    CountryItem("Malawi", "🇲🇼", "+265"),
    CountryItem("Malaysia", "🇲🇾", "+60"),
    CountryItem("Maldives", "🇲🇻", "+960"),
    CountryItem("Mali", "🇲🇱", "+223"),
    CountryItem("Malta", "🇲🇹", "+356"),
    CountryItem("Marshall Islands", "🇲🇭", "+692"),
    CountryItem("Mauritania", "🇲🇷", "+222"),
    CountryItem("Mauritius", "🇲🇺", "+230"),
    CountryItem("Mexico", "🇲🇽", "+52"),
    CountryItem("Micronesia", "🇫🇲", "+691"),
    CountryItem("Moldova", "🇲🇩", "+373"),
    CountryItem("Monaco", "🇲🇨", "+377"),
    CountryItem("Mongolia", "🇲🇳", "+976"),
    CountryItem("Montenegro", "🇲🇪", "+382"),
    CountryItem("Morocco", "🇲🇦", "+212"),
    CountryItem("Mozambique", "🇲🇿", "+258"),
    CountryItem("Myanmar", "🇲🇲", "+95"),

    CountryItem("Namibia", "🇳🇦", "+264"),
    CountryItem("Nauru", "🇳🇷", "+674"),
    CountryItem("Nepal", "🇳🇵", "+977"),
    CountryItem("Netherlands", "🇳🇱", "+31"),
    CountryItem("New Zealand", "🇳🇿", "+64"),
    CountryItem("Nicaragua", "🇳🇮", "+505"),
    CountryItem("Niger", "🇳🇪", "+227"),
    CountryItem("Nigeria", "🇳🇬", "+234"),
    CountryItem("North Korea", "🇰🇵", "+850"),
    CountryItem("North Macedonia", "🇲🇰", "+389"),
    CountryItem("Norway", "🇳🇴", "+47"),

    CountryItem("Oman", "🇴🇲", "+968"),

    CountryItem("Pakistan", "🇵🇰", "+92"),
    CountryItem("Palau", "🇵🇼", "+680"),
    CountryItem("Panama", "🇵🇦", "+507"),
    CountryItem("Papua New Guinea", "🇵🇬", "+675"),
    CountryItem("Paraguay", "🇵🇾", "+595"),
    CountryItem("Peru", "🇵🇪", "+51"),
    CountryItem("Philippines", "🇵🇭", "+63"),
    CountryItem("Poland", "🇵🇱", "+48"),
    CountryItem("Portugal", "🇵🇹", "+351"),

    CountryItem("Qatar", "🇶🇦", "+974"),

    CountryItem("Romania", "🇷🇴", "+40"),
    CountryItem("Russia", "🇷🇺", "+7"),
    CountryItem("Rwanda", "🇷🇼", "+250"),

    CountryItem("Saint Kitts and Nevis", "🇰🇳", "+1-869"),
    CountryItem("Saint Lucia", "🇱🇨", "+1-758"),
    CountryItem("Saint Vincent and the Grenadines", "🇻🇨", "+1-784"),
    CountryItem("Samoa", "🇼🇸", "+685"),
    CountryItem("San Marino", "🇸🇲", "+378"),
    CountryItem("Sao Tome and Principe", "🇸🇹", "+239"),
    CountryItem("Saudi Arabia", "🇸🇦", "+966"),
    CountryItem("Senegal", "🇸🇳", "+221"),
    CountryItem("Serbia", "🇷🇸", "+381"),
    CountryItem("Seychelles", "🇸🇨", "+248"),
    CountryItem("Sierra Leone", "🇸🇱", "+232"),
    CountryItem("Singapore", "🇸🇬", "+65"),
    CountryItem("Slovakia", "🇸🇰", "+421"),
    CountryItem("Slovenia", "🇸🇮", "+386"),
    CountryItem("Solomon Islands", "🇸🇧", "+677"),
    CountryItem("Somalia", "🇸🇴", "+252"),
    CountryItem("South Africa", "🇿🇦", "+27"),
    CountryItem("South Korea", "🇰🇷", "+82"),
    CountryItem("South Sudan", "🇸🇸", "+211"),
    CountryItem("Spain", "🇪🇸", "+34"),
    CountryItem("Sri Lanka", "🇱🇰", "+94"),
    CountryItem("Sudan", "🇸🇩", "+249"),
    CountryItem("Suriname", "🇸🇷", "+597"),
    CountryItem("Sweden", "🇸🇪", "+46"),
    CountryItem("Switzerland", "🇨🇭", "+41"),
    CountryItem("Syria", "🇸🇾", "+963"),

    CountryItem("Taiwan", "🇹🇼", "+886"),
    CountryItem("Tajikistan", "🇹🇯", "+992"),
    CountryItem("Tanzania", "🇹🇿", "+255"),
    CountryItem("Thailand", "🇹🇭", "+66"),
    CountryItem("Timor-Leste", "🇹🇱", "+670"),
    CountryItem("Togo", "🇹🇬", "+228"),
    CountryItem("Tonga", "🇹🇴", "+676"),
    CountryItem("Trinidad and Tobago", "🇹🇹", "+1-868"),
    CountryItem("Tunisia", "🇹🇳", "+216"),
    CountryItem("Turkey", "🇹🇷", "+90"),
    CountryItem("Turkmenistan", "🇹🇲", "+993"),
    CountryItem("Tuvalu", "🇹🇻", "+688"),

    CountryItem("Uganda", "🇺🇬", "+256"),
    CountryItem("Ukraine", "🇺🇦", "+380"),
    CountryItem("United Arab Emirates", "🇦🇪", "+971"),
    CountryItem("United Kingdom", "🇬🇧", "+44"),
    CountryItem("United States", "🇺🇸", "+1"),
    CountryItem("Uruguay", "🇺🇾", "+598"),
    CountryItem("Uzbekistan", "🇺🇿", "+998"),

    CountryItem("Vanuatu", "🇻🇺", "+678"),
    CountryItem("Vatican City", "🇻🇦", "+379"),
    CountryItem("Venezuela", "🇻🇪", "+58"),
    CountryItem("Vietnam", "🇻🇳", "+84"),

    CountryItem("Yemen", "🇾🇪", "+967"),

    CountryItem("Zambia", "🇿🇲", "+260"),
    CountryItem("Zimbabwe", "🇿🇼", "+263")
)
